print('hello world')
print("i spent huge amount of time trying to install python")
print ("Mr hamza is a great mentor. he is patient and loves coding")
print("   /|")
print("  / |")
print(" /  |")
print("/___|")
X = (hello)
print(x)